"""Drift contract for Aider's analytics command events."""

from __future__ import annotations

import ast
import json
from pathlib import Path

import yaml

from traceforge.adapters.mapped_json import MappedJsonAdapter
from traceforge.types import EventKind

MAPPING_PATH = (
    Path(__file__).resolve().parents[2] / "src" / "traceforge" / "mappings" / "aider.yaml"
)

# Command declarations extracted from Aider-AI/aider@a4be6ccd87ebaa59b361f3f028d116ce1761b626
# (tag v0.86.0), aider/commands.py. Aider's Commands.get_commands() exposes every
# cmd_* method after replacing underscores with hyphens.
AIDER_V086_COMMANDS_SOURCE = """
class Commands:
    def cmd_add(self): ...
    def cmd_architect(self): ...
    def cmd_ask(self): ...
    def cmd_chat_mode(self): ...
    def cmd_clear(self): ...
    def cmd_code(self): ...
    def cmd_commit(self): ...
    def cmd_context(self): ...
    def cmd_copy(self): ...
    def cmd_copy_context(self): ...
    def cmd_diff(self): ...
    def cmd_drop(self): ...
    def cmd_edit(self): ...
    def cmd_editor(self): ...
    def cmd_editor_model(self): ...
    def cmd_exit(self): ...
    def cmd_git(self): ...
    def cmd_help(self): ...
    def cmd_lint(self): ...
    def cmd_load(self): ...
    def cmd_ls(self): ...
    def cmd_map(self): ...
    def cmd_map_refresh(self): ...
    def cmd_model(self): ...
    def cmd_models(self): ...
    def cmd_multiline_mode(self): ...
    def cmd_paste(self): ...
    def cmd_quit(self): ...
    def cmd_read_only(self): ...
    def cmd_reasoning_effort(self): ...
    def cmd_report(self): ...
    def cmd_reset(self): ...
    def cmd_run(self): ...
    def cmd_save(self): ...
    def cmd_settings(self): ...
    def cmd_test(self): ...
    def cmd_think_tokens(self): ...
    def cmd_tokens(self): ...
    def cmd_undo(self): ...
    def cmd_voice(self): ...
    def cmd_weak_model(self): ...
    def cmd_web(self): ...
"""


def _load_mapping() -> dict:
    with open(MAPPING_PATH) as mapping_file:
        return yaml.safe_load(mapping_file)


def _emitted_command_events() -> set[str]:
    tree = ast.parse(AIDER_V086_COMMANDS_SOURCE)
    methods = {
        node.name
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef) and node.name.startswith("cmd_")
    }
    return {f"command_{method[4:].replace('_', '-')}" for method in methods}


def test_explicit_command_mappings_are_emitted_by_aider_v086():
    """A mapped command must resolve to a cmd_* method before Aider logs it."""
    mapping = _load_mapping()
    mapped_commands = {name for name in mapping["events"] if name.startswith("command_")}

    dead_commands = mapped_commands - _emitted_command_events()

    assert not dead_commands, f"aider.yaml maps commands Aider cannot emit: {dead_commands}"


def test_unmapped_aider_commands_preserve_raw_fallback():
    """Real cmd_* methods need not be explicit mappings; unknown variants stay observable."""
    mapping = _load_mapping()
    assert mapping["default_kind"] == "raw"
    assert "command_lint" in _emitted_command_events()
    assert "command_lint" not in mapping["events"]

    adapter = MappedJsonAdapter.from_yaml(str(MAPPING_PATH), session_id="aider-contract")
    raw_event = {
        "event": "command_lint",
        "properties": {},
        "user_id": "user-1",
        "time": 1717236000,
    }

    events = list(adapter.parse(json.dumps(raw_event)))

    assert len(events) == 1
    assert events[0].kind == EventKind.RAW
    assert events[0].metadata.raw_kind == "command_lint"
